#pragma config(Motor,  port1,           RightTread,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           Scoop,         tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port3,           Servo1,        tmotorServoStandard, openLoop)
#pragma config(Motor,  port10,          LeftTread,    tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "types.h"
#include "inputs.c"
#include "treadcontrols.c"

bool isScoopMode = false;

#define ScoopSpeed 127

task main()
{
  JoystickValues js;
  ButtonValues buttons;
  while(true)
  {
    sleep(5);
    getJoystickValues(js);
    getButtonValues(buttons);
    // FIXME:  Kludge to move the scoop
    motor[Scoop] = buttons.R1 ? ScoopSpeed : buttons.R2 ? -ScoopSpeed : 0;
    // TODO:  if (treadMode) move treads, if (scoopMode) move scoop
    moveTreads(js, buttons);
  }
}
